name: Create New Blog Post
on: [workflow_dispatch]
jobs:
  create_post:
    env: # Or as an environment variable
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
    name: Create New Post
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install OS Packages
        run: sudo apt install python3 python3-pip
      - name: Install Python Packages
        run: pip3 install -r requirements.py.txt
      - name: Generate New Post
        run: python3 new_post.py
      - name: Commit any chages
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/posts/*
          git diff-index --quiet HEAD || (git commit -a -m'[CI] add new post' --allow-empty && git push -f)