name: Create New Blog Post
on: [workflow_dispatch]
jobs:
  create_post:
    name: Create New Post
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Show Directories
        run: pwd && ls -l
