name: Create New Blog Post
on: [workflow_dispatch]
jobs:
  create_post:
    name: Create New Post
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install OS Packages
        run: sudo apt install python3 python3-pip
      - name: Install Python Packages
        run: pip3 install -r requirements.py.txt
      - name: Generate New Post
        run: python3 new_post.py
      - name: Commit any chages
        run: |
          git config --global user.name "GitHub Actions"
          git diff-index --quiet HEAD || (git commit -a -m'[CI] add new post' --allow-empty && git push -f)